language: node_js
sudo: false
node_js:
  - "6.1"
install:
  - npm install
script:
  - npm test
services:
  - mongodb
before_script:
  - sleep 2
  - mongo mydb_test --eval 'db.addUser("travis", "test");'